### PR TITLE
Use nmcli on linux

### PR DESCRIPTION
**Pull request by stuartf**
nmcli comes with the network-manager package so no need to install other packages or grep network-manager's config

### CODE REVIEW

**Comment by sdushantha** [comment]
Thank you for this fix!

**Comment by littlediobolic** [comment]
I don't believe this works properly. `nmcli -t -f ssid dev wifi` is giving me the output of all of my SSID's not just the connected one.

**Comment by sdushantha** [comment]
@littlediobolic 
I'm thinking of dropping support for Linux for the time being. We can bring back support for Linux once we find a stable solution. What do you think?

**Comment by littlediobolic** [comment]
Its ultimately your choice, but I think its worth spending some time on a more fleshed out solution in a PR and do some more thorough testing to ensure the changes made work on most major distros. Unfortunately network management can vary from device to device making it hard to account for everything. For instance, the Raspberry Pi doesnt even use NetworkManager at all to manager Wifi AFAIK. I think it would be best to revert to a working state for now and see what comes up.

**Comment by sdushantha** [comment]
I have removed support for Linux in #23

**Pull request merged**
