### PR TITLE
added --path parameter to allow users to specify a directory to save the image to

### PR DESCRIPTION
**Pull request by hallur**
when I ran `wifi-password --qrcode --image` the image was saved to my home directory so I added a CLI parameter so the user can control which directory the image will be saved to

### CODE REVIEW

**Comment by sdushantha** [comment]
Hi @hallur,

I appreciate you taking the effort to create this PR. I think this is a great idea especially for users who want to integrate `wifi-password` into their scripts. 

I think this PR could be improved by renaming the `--image-dir` parameter to `--path` so that users can provide the path to the dir and the name of the file since that is how the majority of the command-line programs behave.

**Comment by hallur** [comment]
valid point - I renamed the parameter to --path 👍

**Comment by movatica** [comment]
May I suggest to use a [FileType argument](https://docs.python.org/3/library/argparse.html#filetype-objects) instead?

This way, you get a writability test, path handling and all for free.

**Comment by movatica** [comment]
I would also recommend, to just use one argument for everything:
If there is an image path set, use that. If not, output to the commandline. No need for an additional boolean parameter, except if you want both at the same time. If that is the case, I would change the boolean one to enable the commandline output explicitly, instead of disabling it, e.g.:

- `--show-qr`: show qr code on the commandline
- `--save-qr image.png`: save qr code into image file `path`
- ``: do neither.
- `--show-qr --save-qr image.png`: do both

**Comment by hallur** [comment]
> 
> 
> May I suggest to use a [FileType argument](https://docs.python.org/3/library/argparse.html#filetype-objects) instead?
> 
> This way, you get a writability test, path handling and all for free.

I thought about that but the FileType argument only works for file and not directories unless I'm mistaken?

**Comment by hallur** [comment]
> 
> 
> I would also recommend, to just use one argument for everything:
> If there is an image path set, use that. If not, output to the commandline. No need for an additional boolean parameter, except if you want both at the same time. If that is the case, I would change the boolean one to enable the commandline output explicitly, instead of disabling it, e.g.:
> 
>     * `--show-qr`: show qr code on the commandline
> 
>     * `--save-qr image.png`: save qr code into image file `path`
> 
>     * ``: do neither.
> 
>     * `--show-qr --save-qr image.png`: do both

sounds good. what do you think @sdushantha?

**Comment by movatica** [comment]
> > May I suggest to use a [FileType argument](https://docs.python.org/3/library/argparse.html#filetype-objects) instead?
> > This way, you get a writability test, path handling and all for free.
> 
> I thought about that but the FileType argument only works for files and not directories unless I'm mistaken?

Yes, it's for files. But as the script does output one file and not many, I do not see the point of asking for the directory but force a hardcoded filename, instead of just getting the whole path from the user?

**Comment by sdushantha** [comment]
All of this sounds great!

Let's go with @movatica's recommendation to just use one argument for everything and use a FileType argument. I think this will make it must easier for people to understand the usage of the tool much clearer.

**Comment by sdushantha** [comment]
Just a small update on this:
`--save-qr` should save the files as `SSID_NAME.png` to the current directory. This way, users do not always have to provide a file name.

**Comment by sdushantha** [comment]
@movatica @hallur 
I have worked on this in #47. Test it out and let it me know if you guys encounter any issues.

**Pull request closed without merging**
