### PR TITLE
Fix potential bug with os not in english

### PR DESCRIPTION
**Pull request by celianvdb**
Hi,
After some tests with your tool, I discovered a little problem for some setups.

To detect SSID, it's using `nmcli -t -f active,ssid dev wifi | egrep '^yes' | cut -d\: -f2`.
The problem is that `nmcli -t -f active,ssid dev wifi` output depends of language. In english it will return `SSID yes/no` but for example in french it return `SSID oui/non`.

To fix that I'm forcing the language using LANG env variable.

### CODE REVIEW

**Comment by sdushantha** [comment]
> To fix that I'm forcing the language using LANG env variable.

Thank you, that seems like a useful addition.
Does this affect Windows? I'm not so familiar with environment variables on Windows.

**Comment by celianvdb** [comment]
I'm not familiar with environment variables in Windows too but as I know, it's also using LANG=C and have the same effect as on linux.

**Comment by sdushantha** [comment]
There seems to be a conflict due to the latest commit. Could you resolve the conflicts? 
I'll make sure to merge this PR as soon as they've been resolved :)

**Comment by DamienAllonsius** [comment]
This is a nice PR, I have the same problem !
Notice that it's still possible to retrieve the password using the option `--ssid` ;)
`wifi-password --ssid my_wifi_name` does the job

**Comment by celianvdb** [comment]
> This is a nice PR, I have the same problem !
> Notice that it's still possible to retrieve the password using the option `--ssid` ;)
> `wifi-password --ssid my_wifi_name` does the job, whatever your terminal language is

Exactly, it only affect the autodetection of the ssid.

> There seems to be a conflict due to the latest commit. Could you resolve the conflicts?
> I'll make sure to merge this PR as soon as they've been resolved :)

Fixed @sdushantha , sorry for the delay

**Comment by DamienAllonsius** [comment]
good job

**Comment by sdushantha** [comment]
@celianvdb When you dealt with the merge conflict you deleted a lot of lines of code and a file that is needed. Not quiet sure why you did that, I'm guessing that was a mistake?

**Comment by celianvdb** [comment]
Oh, big mistake yes, I do fix that today, sorry

**Comment by celianvdb** [comment]
Fixed

**Comment by sdushantha** [comment]
I see that you made the changes in order to fix the deletions but when I check the "[Files changed](https://github.com/sdushantha/wifi-password/pull/25/files)" tab in this PR it still says that a lot of things have been removed. Maybe you could open a new PR?

**Comment by celianvdb** [comment]
Strange 🤔 IDK how to fix that, so, yes will try to open another PR.

**Pull request closed without merging**
